name = "gta-vc"
main = "worker.js"
compatibility_date = "2026-08-28"

routes = [
  { pattern = "gta-vc.colaco.se", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SAVES"
id = "4c7cc128ecdc43b185c678bc80a07c02"

[[r2_buckets]]
binding = "GAME"
bucket_name = "gta-vc-assets"